# Generated by Django 3.1.7 on 2021-03-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_user', models.IntegerField(verbose_name='cpu_user')),
                ('cpu_sys', models.IntegerField(verbose_name='cpu_sys')),
                ('cpu_wait', models.IntegerField(verbose_name='cpu_wait')),
                ('cpu_steal', models.IntegerField(verbose_name='cpu_steal')),
                ('cpu_idle', models.IntegerField(verbose_name='cpu_idle')),
                ('cpu_util', models.IntegerField(verbose_name='cpu_util')),
                ('time', models.IntegerField(verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'cpu info',
                'db_table': 'collect_cpu_info',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='IoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50, verbose_name='block device name')),
                ('io_rs', models.IntegerField(verbose_name='io read second')),
                ('io_ws', models.IntegerField(verbose_name='io write second')),
                ('io_await', models.IntegerField(verbose_name='io await')),
                ('io_util', models.IntegerField(verbose_name='io utilization')),
                ('time', models.IntegerField(verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'block device io info',
                'db_table': 'collect_io_info',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='MemoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_total', models.IntegerField(verbose_name='mem total')),
                ('mem_free', models.IntegerField(verbose_name='mem free')),
                ('mem_used', models.IntegerField(verbose_name='mem used')),
                ('mem_buff', models.IntegerField(verbose_name='mem buff')),
                ('mem_util', models.FloatField(verbose_name='mem util')),
                ('mem_cache', models.IntegerField(verbose_name='mem cache')),
                ('time', models.IntegerField(verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'memory info',
                'db_table': 'collect_mem_info',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='NetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50, verbose_name='interface name')),
                ('in_bytes', models.IntegerField(verbose_name='in bytes')),
                ('in_packets', models.IntegerField(verbose_name='in packets')),
                ('in_errors', models.IntegerField(verbose_name='in errors')),
                ('in_drops', models.IntegerField(verbose_name='in drops')),
                ('out_bytes', models.IntegerField(verbose_name='out bytes')),
                ('out_packets', models.IntegerField(verbose_name='out packets')),
                ('out_errors', models.IntegerField(verbose_name='out errors')),
                ('out_drops', models.IntegerField(verbose_name='out drops')),
                ('time', models.IntegerField(verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'net info',
                'db_table': 'collect_net_info',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='SysLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load1', models.FloatField(verbose_name='load1')),
                ('load5', models.FloatField(verbose_name='load5')),
                ('load15', models.FloatField(verbose_name='load15')),
                ('time', models.IntegerField(verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'system load',
                'db_table': 'collect_sys_load',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TcpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcp_active', models.IntegerField(verbose_name='tcp active')),
                ('tcp_passive', models.IntegerField(verbose_name='tcp passive')),
                ('tcp_inseq', models.IntegerField(verbose_name='tcp in seq')),
                ('tcp_outseq', models.IntegerField(verbose_name='tcp out seq')),
                ('tcp_established', models.IntegerField(verbose_name='tcp established')),
                ('tcp_retran', models.IntegerField(verbose_name='tcp retransfer')),
                ('time', models.IntegerField(verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'tcp session info',
                'db_table': 'collect_tcp_info',
                'ordering': ['time'],
            },
        ),
    ]
