# Generated by Django 3.1.7 on 2021-03-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcpinfo',
            old_name='tcp_inseq',
            new_name='tcp_inseg',
        ),
        migrations.RenameField(
            model_name='tcpinfo',
            old_name='tcp_outseq',
            new_name='tcp_outseg',
        ),
    ]
